// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_API_KEY',
    appId: '1:735538348786:web:cc3b3f594199c45615066b',
    messagingSenderId: '735538348786',
    projectId: 'kaeru-kpss',
    authDomain: 'kaeru-kpss.firebaseapp.com',
    storageBucket: 'kaeru-kpss.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_API_KEY',
    appId: '1:735538348786:android:2d4c9d2e0c1273f715066b',
    messagingSenderId: '735538348786',
    projectId: 'kaeru-kpss',
    storageBucket: 'kaeru-kpss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_API_KEY',
    appId: '1:735538348786:ios:0997c5989163a08415066b',
    messagingSenderId: '735538348786',
    projectId: 'kaeru-kpss',
    storageBucket: 'kaeru-kpss.firebasestorage.app',
    iosBundleId: 'com.kaeru.kpss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_API_KEY',
    appId: '1:735538348786:ios:0997c5989163a08415066b',
    messagingSenderId: '735538348786',
    projectId: 'kaeru-kpss',
    storageBucket: 'kaeru-kpss.firebasestorage.app',
    iosBundleId: 'com.kaeru.kpss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_API_KEY',
    appId: '1:735538348786:web:d74eafab21cb5d5b15066b',
    messagingSenderId: '735538348786',
    projectId: 'kaeru-kpss',
    authDomain: 'kaeru-kpss.firebaseapp.com',
    storageBucket: 'kaeru-kpss.firebasestorage.app',
  );
}
